### ISSUE TITLE
Создать докер контейнер с развернутым и запущенным приложением

### ISSUE THREAD

**Issue by zmm** [moevm/rePullet#12]
Необходимо создать и запушить в докерхаб контейнер (с возможностью подключения своего github ключа oauth  и полностью запущенным приложением)

**Comment by pr3sto** [comment]
Done

40fc69a677f02a64ad11ab6dd76b7b543821c7e7
324559b96d8939217f0caf2ac87f21965bbda890

https://hub.docker.com/u/pr3sto/
