### ISSUE TITLE
Неправильные значения отображаемых элементов dashboard

### ISSUE THREAD

**Issue by BassinD** [moevm/rePullet#16]
![image](https://user-images.githubusercontent.com/29598797/31408794-6383155a-ae12-11e7-894d-579bd52bb4c9.png)
Значения этого поля hardcoded в файле table.html 
Их либо убрать (так как нет реализации случая, когда отображается часть элементов), либо сделать отображение соответствующим действительности

**Comment by backsapc** [comment]
Значение этого поля убрано, до момента реализации функции.
