### ISSUE TITLE
Удаление репозитория с dashboard не работает

### ISSUE THREAD

**Issue by zmm** [moevm/rePullet#5]
Сейчас вот здесь http://127.0.0.1:20000/dashboard#  не работает кнопка удаления репозитория

**Comment by BassinD** [comment]
Думаю это не баг, так как просто нет просто реализации метода. Более того нет реализации ни для одной из кнопок 
![image](https://user-images.githubusercontent.com/29598797/31403363-8f2d8c50-ae01-11e7-885d-4167066b00c1.png)

**Comment by pr3sto** [comment]
#15 - реализация методов

**Comment by pr3sto** [comment]
@BassinD наверное, можно закрыть эту issue
