### ISSUE TITLE
 повисло и не развисло http://pullet.tw1.ru/view/moevm/pr1-2016-6303

### ISSUE THREAD

**Issue by zmm** [moevm/rePullet#7]

**Comment by BassinD** [comment]
In progress

**Comment by BassinD** [comment]
Оно не зависает, а очень долго работает в связи с тем что алгоритм как минимум 2 раза проходит по каждому пул-реквесту и собирает о нем информацию, а так как их здесь около 200 и время на обработку в среднем около секунды (зависит от количества данных), то получается довольно долго.
![image](https://user-images.githubusercontent.com/29598797/32627831-e1eff99a-c5a4-11e7-8a73-5b6c1ed7aa89.png)
